[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "majutsushi/tagbar"

[[plugins]]
repo = "junegunn/fzf"
build = "./install --all"

[[plugins]]
repo = "junegunn/fzf.vim"
depends = "fzf"

[[plugins]]
repo = "w0rp/ale"

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "vim-airline/vim-airline-themes"

[[plugins]]
repo = "ryanoasis/vim-devicons"

[[plugins]]
repo = "tpope/vim-commentary"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "reireias/vim-cheatsheet"

[[plugins]]
repo = "plasticboy/vim-markdown"

[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ["markdown", "pandoc.markdown", "rmd"]
build = "sh -c 'cd app && yarn install'"

[[plugins]]
repo = "godlygeek/tabular"
