[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "majutsushi/tagbar"

[[plugins]]
repo = "junegunn/fzf"
build = "./install --all"

[[plugins]]
repo = "junegunn/fzf.vim"
depends = "fzf"

# [[plugins]]
# repo = "w0rp/ale"

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "vim-airline/vim-airline-themes"

[[plugins]]
repo = "ryanoasis/vim-devicons"

[[plugins]]
repo = "tpope/vim-commentary"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "reireias/vim-cheatsheet"

[[plugins]]
repo = "plasticboy/vim-markdown"

[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ["markdown", "pandoc.markdown", "rmd"]
build = "sh -c 'cd app && yarn install'"

[[plugins]]
repo = "godlygeek/tabular"

[[plugins]]
repo = "easymotion/vim-easymotion"

[[plugins]]
repo = "prabirshrestha/vim-lsp"

[[plugins]]
repo = "mattn/vim-lsp-settings"

[[plugins]]
repo = "mattn/vim-lsp-icons"

[[plugins]]
repo = "prabirshrestha/asyncomplete.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-lsp.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-file.vim"

[[plugins]]
repo = "Shougo/neco-syntax"

[[plugins]]
repo = "prabirshrestha/asyncomplete-necosyntax.vim"

[[plugins]]
repo = "Shougo/neco-vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete-necovim.vim"

[[plugins]]
repo = "Shougo/neosnippet.vim"

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "prabirshrestha/asyncomplete-neosnippet.vim" 

[[plugins]]
repo = "morhetz/gruvbox"

[[plugins]]
repo = 'mbbill/undotree'

[[plugins]]
repo = 'mattn/vim-sonictemplate'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "tpope/vim-rhubarb"

[[plugins]]
repo = "miyakogi/seiya.vim"

[[plugins]]
repo = "xolox/vim-misc"

[[plugins]]
repo = "xolox/vim-session"

[[plugins]]
repo = "glidenote/memolist.vim"

[[plugins]]
repo = "chrisbra/csv.vim"

[[plugins]]
repo = "cocopon/iceberg.vim"
