# [[plugins]]
# repo = "Shougo/deoplete.nvim"
# hook_source = "let g:deoplete#enable_at_startup = 1"
# on_i = 1

# [[plugins]]
# repo = "OmniSharp/omnisharp-vim"
# on_ft = ["cs"]
# build = "xbuild server/OmniSharp.sln"

# [[plugins]]
# repo = "Robzz/deoplete-omnisharp"
# on_source = ["deoplete.nvim"]

[[plugins]]
repo = "lervag/vimtex"
on_ft = ["tex"]
hook_post_source = '''
let g:vimtex_fold_envs = 0
#let g:vimtex_view_general_viewer = 'displayline'
#let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ]}
let g:vimtex_compiler_progname = 'nvr'
 '''
