[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "majutsushi/tagbar"

[[plugins]]
repo = "junegunn/fzf"
build = "./install --all"

[[plugins]]
repo = "junegunn/fzf.vim"
depends = "fzf"

[[plugins]]
repo = "w0rp/ale"

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "vim-airline/vim-airline-themes"

[[plugins]]
repo = "ryanoasis/vim-devicons"
